name: Deploy to Yandex Cloud Function

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install YCNF CLI
      run: npm install -g ycnf
      
    - name: Setup Yandex Cloud CLI
      run: |
        # Install YC CLI
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
        
    - name: Configure Yandex Cloud
      run: |
        # Create YC config directory
        mkdir -p ~/.config/yandex-cloud
        
        # Create config file with service account key
        cat > ~/.config/yandex-cloud/config.yaml << EOF
        current: default
        profiles:
          default:
            token: ${{ secrets.YC_TOKEN }}
            cloud-id: ${{ secrets.YC_CLOUD_ID }}
            folder-id: ${{ secrets.YC_FOLDER_ID }}
        EOF
        
    - name: Create environment file
      run: |
        echo "YC_FOLDER_ID=${{ secrets.YC_FOLDER_ID }}" > .env
        if [ -n "${{ secrets.YC_PROFILE }}" ]; then
          echo "YC_PROFILE=${{ secrets.YC_PROFILE }}" >> .env
        fi
        
    - name: Verify YC CLI configuration
      run: |
        yc config list
        
    - name: Deploy function
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Deploying function to Yandex Cloud..."
        ycnf public
        
    - name: Check function status
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Checking function status..."
        ycnf check
        
    - name: Test deployment (dry run)
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
      run: |
        echo "This is a dry run for PR. Function would be deployed on merge to main."
        echo "Function configuration:"
        cat .functionconfig.json